include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    sort_constructors_first: true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables: true
