name: kidtoon
description: KidToon - Cartoon Yourself & Learn About the World!
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.3.1
  image_picker: ^1.0.7
  flutter_tts: ^4.0.2
  material_color_utilities: ^0.12.0
  meta: ^1.17.0
  vector_math: ^2.1.4
  leak_tracker: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  lints: ^3.0.0
  test_api: ^0.7.6

flutter:
  uses-material-design: true
  assets:
    - assets/mascots/
    - assets/backgrounds/
    - assets/stickers/
    - assets/icons/
    - assets/lessons/
  generate: true

# Localization configuration for Flutter gen-l10n tool
localizations:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  supported-locales:
    - en
    - es
    - fr
    - ar
    - zh
    - hi
    - sw
